default:
  is_secure: on

index:
  is_secure: off

image:
  is_secure: off

show:
  is_secure: off

original:
  is_secure: off

info:
  is_secure: off

tags:
  is_secure: off
  
# Credentials for uploading, implemented in the code: you must
# be a member of the group specified by app_pkMedia_upload_group.
# If that setting does not exist, then any logged-in user can upload.

# Credentials for editing, implemented in the code: you can edit if you are
# the person who put it there in the first place, or you are a member
# of the app_pkMedia_admin_group. (If that is not configured, any
# logged-in user is a media admin.)
