<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkMediaItem extends BasepkMediaItem
{
  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->getOwnerId())
    {
      $user = sfContext::getInstance()->getUser();
      if ($user->getGuardUser())
      {
        $this->setOwnerId($user->getGuardUser()->getId());
      }
    }
    // Let the culture be the user's culture
    return pkZendSearch::saveInDoctrineAndLucene($this, null, $conn);
  }

  public function doctrineSave($conn)
  {
    return parent::save($conn);
  }

  public function delete(Doctrine_Connection $conn = null)
  {
    $ret = pkZendSearch::deleteFromDoctrineAndLucene($this, null, $conn);
    $this->clearImageCache();
    // Don't even think about trashing the original until we know
    // it's gone from the db and so forth
    unlink($this->getOriginalPath());
    return $ret;
  }

  public function doctrineDelete($conn)
  {
    return parent::delete($conn);
  }
  
  public function updateLuceneIndex()
  {
    pkZendSearch::updateLuceneIndex($this, array(
      'type' => $this->getType(),
      'title' => $this->getTitle(),
      'description' => $this->getDescription(),
      'credit' => $this->getCredit(),
      'tags' => implode(", ", $this->getTags())
    ));
  }
  
  public function getOriginalPath($format = false)
  {
    if ($format === false)
    {
      $format = $this->getFormat();
    }
    return pkMediaItemTable::getDirectory() . 
      $this->getSlug() . ".original.$format";
  }
  public function clearImageCache($deleteOriginals = false)
  {
    if (!$this->getId())
    {
      return;
    }
    $cached = glob(pkMediaItemTable::getDirectory() . $this->getSlug() . ".*");
    foreach ($cached as $file)
    {
      if (!$deleteOriginals)
      {
        if (strpos($file, ".original.") !== false)
        {
          continue;
        }
      }
      unlink($file); 
    }
  }
  public function preSaveImage($file)
  {
    $formats = array(
      IMAGETYPE_JPEG => "jpg",
      IMAGETYPE_PNG => "png",
      IMAGETYPE_GIF => "gif"
    );
    $data = getimagesize($file);
    if (count($data) < 3)
    {
      return false;
    }
    if (!isset($formats[$data[2]]))
    {
      return false;
    }
    $format = $formats[$data[2]];
    $this->clearImageCache(true);
    $this->width = $data[0];
    $this->height = $data[1];
    $this->format = $format;
    return true;
  }

  public function saveImage($file)
  {
    if (!$this->width)
    {
      $this->preSaveImage($file);
    }
    $result = copy($file, $this->getOriginalPath($this->getFormat()));
    return $result;
  }

  public function getEmbedCode($width, $height, $resizeType, $format = 'jpg')
  {
    if ($height === false)
    {
      // Scale the height
      $height = floor(($width * $this->width / $this->height) + 0.5); 
    }
    // It would be nice if partials could be used for this.
    // Think about whether that's possible.
    if ($this->getType() === 'video')
    {
      // TODO: less YouTube-specific
      $serviceUrl = $this->getServiceUrl();
      $embeddedUrl = $this->youtubeUrlToEmbeddedUrl($serviceUrl);
      return <<<EOM
<object width="$width" height="$height"><param name="movie" value="$embeddedUrl"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="$embeddedUrl" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="$width" height="$height"></embed></object>
EOM
      ;
    }
    elseif ($this->getType() == 'image')
    {
      $controller = sfContext::getInstance()->getController();
      $slug = $this->getSlug();
      return "<img src='" . $controller->genUrl("pkMedia/image?" . 
        http_build_query(
          array("slug" => $slug, 
            "width" => $width, 
            "height" => $height, 
            "resizeType" => $resizeType,
            "format" => $format))) .
            "' />";
    }
    else
    {
      throw Exception("Unknown media type in getEmbedCode: " . $this->getType());
    }
  }
  protected function youtubeUrlToEmbeddedUrl($url)
  {
    $url = str_replace("/watch?v=", "/v/", $url);
    $url .= "&fs=1";
    return $url;
  }
  public function userHasPrivilege($privilege, $user = false)
  {
    if ($user === false)
    {
      $user = sfContext::getInstance()->getUser();
    }
    if ($privilege === 'view')
    {
      if ($this->getViewIsSecure())
      {
        if (!$user->isAuthenticated())
        {
          return false;
        }
      }
      return true;
    }
    if ($user->hasCredential('media_admin'))
    {
      return true;
    }
    $guardUser = $user->getGuardUser();
    if (!$guardUser)
    {
      return false;
    }
    if ($this->getOwnerId() === $guardUser->getId())
    {
      return true;
    }
  }
}
